[colors.bright]
black = "#5C6773"
blue = "#8ca9bf"
cyan = "#73c5e2"
green = "#add488"
magenta = "#e2afec"
red = "#e16f7e"
white = "#fcfcfc"
yellow = "#E6B673"

[colors.cursor]
cursor = "#ebdbb2"
text = "#282828"

[colors.normal]
black = "#0F1419"
blue = "#4877b1"
cyan = "#00bcd4"
green = "#5ca75b"
magenta = "#a660c3"
red = "#e14245"
white = "#a9a9aa"
yellow = "#FFB454"

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"